import csv
from pathlib import Path
R=Path('/root/autodl-fs/RewardLens');B=R/'results/phase2/paper_analysis';O=R/'paper';O.mkdir(parents=True,exist_ok=True)
rows=list(csv.DictReader((B/'model_summary.csv').open()))
def f(r,k):return float(r[k])
tab='\n'.join('| %s | %.4f | %.4f | %.4f | %.4f | %.4f | %.4f |'%(r['model'],f(r,'A_macro'),f(r,'PFC_macro'),f(r,'PSC_macro'),f(r,'U2_macro'),f(r,'U4_macro'),f(r,'U8_macro')) for r in rows)
docs={'abstract_v0.md':'# Abstract v0\n\nMultimodal reward-model evaluation usually emphasizes preference accuracy, but accuracy alone cannot establish whether a model relies on intended visual evidence. Controlled factor-specific interventions reveal heterogeneous evidence-dependency profiles, including near-accuracy-matched models with materially different relevant-evidence dependence. PFC and PSC show stronger descriptive associations with downstream utility than static accuracy in this four-model checkpoint, but N=4 is insufficient for independent incremental-validity inference. Expanded multi-family experiments provide confirmatory analysis.\n','introduction_v0.md':'# Introduction\n\nPreference accuracy is necessary but not sufficient for multimodal reward models. A judge may be correct while relying on irrelevant visual cues. Our central question is whether conventional accuracy can hide materially different visual-dependency behavior.\n','method_v0.md':'# Method\n\nRelevant and irrelevant interventions yield PFC and PSC; conditional variants condition on base correctness. Static accuracy is independent. U@8 is frozen Best-of-N utility and U@2/U@4 are derived from the same N=8 graph. Four-model RQ2 is descriptive only because U ~ A + PFC + PSC is saturated at N=4.\n','experiments_v0.md':'# Experimental setup\n\nQwen3-VL-4B, Gemma-3-4B, Molmo-7B, and Skywork-VL-Reward-7B each completed 800 static examples and 800 downstream pools. Factors are fixed as Count, Attribute, Spatial, Presence.\n','results_v0.md':'# Results v0\n\n## RQ1\nQwen and Skywork have A=0.8575 and 0.8450 (delta 1.25 pp), PFC=0.7875 and 0.8700 (delta 8.25 pp), and U@8=0.6975 and 0.7513 (delta 5.38 pp).\n\n| Model | A | PFC | PSC | U2 | U4 | U8 |\n|---|---:|---:|---:|---:|---:|---:|\n'+tab+'\n\n## RQ2\nPearson U@8 correlations are A=0.934, PFC=0.978, PSC=0.983; Spearman values are 0.6, 0.8, 0.8. These are descriptive N=4 relationships; no saturated regression inference is claimed.\n\n## RQ3\nPending implementation validation because current diagonal/off-diagonal equality is near machine precision.\n','discussion_v0.md':'# Discussion\n\nThe strongest result is an evaluation blind spot: similar conventional accuracy can conceal different reliance on relevant visual evidence. Utility association motivates, but does not establish, independent predictive value.\n','limitations_v0.md':'# Limitations\n\nFour models are insufficient for formal incremental validity. RQ3 awaits implementation audit. Expanded models, family bootstrap, and leave-one-family-out analysis are pending.\n'}
for n,t in docs.items():(O/n).write_text(t)
(O/'claim_ledger_v0.csv').write_text('claim_id,claim_text,rq,evidence_strength,four_model_status,expanded_status,safe_for_abstract\nC1,Accuracy does not uniquely determine visual dependency,RQ1,SUPPORTED,SUPPORTED,PENDING,YES\nC2,Dependency has independent predictive value beyond accuracy,RQ2,INSUFFICIENT_EVIDENCE,DESCRIPTIVE_ONLY,PENDING,NO\nC3,Dependency-utility relationships are factor-specific,RQ3,INSUFFICIENT_EVIDENCE,PENDING_IMPLEMENTATION_VALIDATION,PENDING,NO\n')
(B/'four_model/rq3_implementation_audit.md').write_text('# RQ3 implementation audit\n\nRQ3 = PENDING IMPLEMENTATION VALIDATION. Raw factor labels and inputs must be traced before interpreting the near machine-precision diagonal/off-diagonal equality.\n')
print('PAPER_V0_CREATED = TRUE')
